name: Analyze Issue

on:
  issue_comment:
    types: [created]

jobs:
  analyze-issue:
    uses: cross-platform-actions/test-workflows/.github/workflows/analyze-issue.yml@master
    permissions:
      contents: read
      issues: write
      id-token: write
    with:
      issue_number: ${{ github.event.issue.number }}
    # secrets: inherit
    # secrets:
    #   anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
